trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: azureagent

    steps:
    # - task: Maven@4
    #   inputs:
    #     azureSubscription: 'payasyougo(c02db223-ae2a-4677-943f-e5864c5361a3)'
    #     mavenPomFile: '$(System.DefaultWorkingDirectory)/pom.xml'
    #     goals: 'test'
    #     publishJUnitResults: true
    #     testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #     javaHomeOption: 'JDKVersion'
    #     mavenVersionOption: 'Default'
    #     mavenAuthenticateFeed: false
    #     effectivePomSkip: false
    #     sonarQubeRunAnalysis: true
    #     sqMavenPluginVersionChoice: 'latest'    
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'atharvdevops/currency-exchange-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        arguments: '--platform linux/arm64'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool: azureagent
      
    steps:

    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        downloadPath: '$(System.ArtifactsDirectory)'
    
    - script: | 
        export KUBECONFIG=/home/atharv/.kube/config
        kubectl config use-context k8stest_dev
        kubectl get ns
      displayName: 'Verify kubectl connectivity'


    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'payasyougo(c02db223-ae2a-4677-943f-e5864c5361a3)'
        azureResourceGroup: 'kubernetes_dev'
        kubernetesCluster: 'k8stest_dev'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/manifests/configuration/kubernetes/deployment.yaml'
        containers: 'atharvdevops/currency-exchange-devops:$(tag)'
   
        